### ISSUE TITLE
"Invalid Date" error in Chrome on OSX

### ISSUE THREAD

**Issue by gapple** [gapple/drupalreleasedate#28]
https://twitter.com/nicholasruunu/status/545610509593378817
https://twitter.com/adammalone/status/552650859364888577

**Comment by dietrichm** [comment]
I have this issue on Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36.

Debugging the JS:

    estimateDate: Invalid Date
    estimateDateString: "2017-01-19T00:00:0001:00"

It appears using `new Date` upon the given date string fails.

**Comment by maartendeblock** [comment]
I have the same issue on Chrome in Windows 8.

The datestring of .when can't be converted to a date object: "2015-01-06T00:17:01-08:00" => "Invalid date"
