### ISSUE TITLE
Remove / hide estimates before 12th Dec

### ISSUE THREAD

**Issue by iant-tui** [gapple/drupalreleasedate#29]
The graph at https://drupalreleasedate.com/chart/estimates shows some fairly wacky estimates made before 12th Dec, which means the scale has to be adjusted to fit them in. If those estimates can be hidden then the remainder of the graph will be more informative.

**Comment by gapple** [comment]
I've just completed #24, which adds a user-adjustable range filter to both the sample and estimate charts
