### ISSUE TITLE
Replace logarithmic issue graph with separate linear graph for majors and criticals.

### ISSUE THREAD

**Issue by Berdir** [gapple/drupalreleasedate#30]
We made *huge* progress with the critical issue count, as the stats clearly show (down from 130 in Nov to 70 now).

However, the current graph does not really show that.

It might have been a good way to show beta blockers and the others on the same graph before, but I think it is just confusing and misleading now.

Suggestion: display two separate linear graphs, one for majors and one for criticals.

**Comment by larowlan** [comment]
:+1:

**Comment by gapple** [comment]
I suppose it's not particularly clear, but you can click on the labels in the legend to [toggle the visibility of each series](https://twitter.com/DrupalReleaseDt/status/478379236072644608).  If only one series is visible it will switch to a linear scale.

**Comment by gapple** [comment]
I've updated the default settings to only show critical issues, since everything else really is supplementary information. 
If you have toggled visibility of any of the series in the past, it's initial state is stored in your browser's local settings and overrides the defaults.

**Comment by Berdir** [comment]
Thanks, that seems like a good change.

One minor thing is that the graph starts at 40, and is a bit misleading due to that, but that's OK I think, we'll hopefulyl get down enough soon for it to move closer to 0 ;)

**Comment by gapple** [comment]
I agree; chart is now fixed to start at 0.
[![Is truncating the Y-axis misleading](https://pbs.twimg.com/media/B3cQNipIIAARU2I.jpg)](https://twitter.com/EstatSaude/status/537916513504989184)
