### ISSUE TITLE
Add stats for closed and opened

### ISSUE THREAD

**Issue by sirtet** [gapple/drupalreleasedate#35]
Sometimes it looks like there's not much activity, numbers going slightly up and down.
If it was possible to also show "closed/opened today|week|month", this would be more informative.

**Comment by gapple** [comment]
The current average pace (over the last 6 months) is an issue resolved every three days, and I don't think the pace has ever been much more than an issue every two days.

With the number of current criticals, limited churn, and relatively soon expected date, I don't think that opened/closed values would provide much value or insight compared to the effort required to track them.
