### ISSUE TITLE
Add tracking 'days-to' to statistics

### ISSUE THREAD

**Issue by macmladen** [gapple/drupalreleasedate#39]
You may add tracking that will present how much days are left to release (as of Aug 5th to estimated Sep 1 is 26 days left to release) so you may track if estimate is approaching or delaying.

**Comment by gapple** [comment]
The [estimates chart](https://drupalreleasedate.com/chart/estimates) shows the history of estimates, as well as their confidence, and shows that the current trend is towards a later release date.
