### ISSUE TITLE
Calculation does not account for Drupal Core release windows.

### ISSUE THREAD

**Issue by alexanderpas** [gapple/drupalreleasedate#42]
As per documentation

https://www.drupal.org/core/dev-cycle

- Release windows for Drupal core are on the first and third Wednesdays of each month. For stable releases, the first Wednesday is a bugfix release window and the third Wednesday is a security release window.
- Once we reach zero critical issues, the first release candidate is tagged on the next of these release windows (whether bugfix or security) to sync up the Drupal 8 release schedule with that of Drupal 6 and 7. (If the next release window is less than 72 hours away, the following one will be used instead.)

At this moment, the calculation does not account for these release windows, showing days outside the release windows instead

**Comment by gapple** [comment]
I think this can be closed as "Won't Fix", since RC1 was released today :+1:
